#!/bin/sh
OLDPATH=$PATH
WHEREAMI=`pwd`
export PATH=$WHEREAMI/node/bin:"$PATH"
NODEINST=`which node`

#TODO extract specific module and only compile that one
sh modules/deterministic/compileall.sh

        echo " [i] using node executable $NODEINST"
        node $@

PATH=$OLDPATH
